Playwright version 1.45.0.

diff --git a/workshop/12_01_Templates.yml b/workshop/12_01_Templates.yml
--- a/workshop/12_01_Templates.yml
+++ b/workshop/12_01_Templates.yml
@@ -110,6 +110,10 @@ stages:
           # Retrieve the output values from the deployment
           ACR_NAME=$(jq --raw-output '.acrName.value' <<< $ACR_CREDENTIALS)
           ACR_URL=$(jq --raw-output '.acrUrl.value' <<< $ACR_CREDENTIALS)
+          if [[ -z $ACR_URL ]]; then
+            echo "Error: ACR_URL is empty"
+            exit 1
+          fi
           echo "Setting ACR_CREDENTIALS for output"
           echo "##vso[task.setvariable variable=acrName;isOutput=true]$ACR_NAME"
           echo "##vso[task.setvariable variable=acrUrl;isOutput=true]$ACR_URL"
