Azure CLI version 2.60.0.

diff --git a/workshop/12_02_Provision_Infrastructure.yml b/workshop/12_02_Provision_Infrastructure.yml
--- a/workshop/12_02_Provision_Infrastructure.yml
+++ b/workshop/12_02_Provision_Infrastructure.yml
@@ -77,5 +77,9 @@ stages:
                   acrName='$(acrName)' acrUrl='$(acrUrl)' acrResourceGroupName='$(acrResourceGroupName)' \
                   executorSecurityPrincipal=${servicePrincipalId} --query properties.outputs)
                 WEBUI_CA_URL=$(jq --raw-output '.webUiCaUrl.value' <<< $DEPLOYMENT_OUTPUT)
+                if [[ -z $WEBUI_CA_URL ]]; then
+                  echo "Error: WEBUI_CA_URL is empty"
+                  exit 1
+                fi
                 echo "##vso[task.setvariable variable=webUiCaUrl;isOutput=true]$WEBUI_CA_URL"
                 echo "WEBUI_CA_URL value is: $WEBUI_CA_URL"
